[package]
name = "gbrs-sfml-gui"
version = "0.2.0"
authors = ["Adam Soutar <adam@overflo.me>"]
edition = "2021"

[dependencies]
gbrs-core = { path = "../core" }
sfml = "0.24.0"
spin = { version = "0.10.0", features = ["spin_mutex"] }
