[package]
name = "gbrs-libretro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libretro-rs = "0.1.3"
gbrs-core = { path = "../core" }

[lib]
crate-type = ["cdylib"]
