[package]
name = "profiling"
version = "0.1.0"
edition = "2018"

[profile.release]
panic = "abort"
opt-level = 3
lto = false
debug = true
split-debuginfo = "packed"

[dependencies]
gbrs-core = { path = "../core", default-features = false, features = ["std"] }
