[package]
name = "gbrs-sdl-gui"
version = "0.2.0"
authors = ["Adam Soutar <adam@overflo.me>"]
edition = "2021"

[dependencies]
gbrs-core = { path = "../core" }
sdl2 = { version = "0.35.2", features = ["bundled"] }
