[package]
name = "gbrs-wasm-gui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gbrs-core = { path = "../core" }
wasm-bindgen = "0.2"
web-sys = { version = "0.3.76", features = ["console", "Window", "Storage"] }
console_error_panic_hook = "0.1.7"
base64 = "0.22.1"